### ISSUE TITLE
Defold README.md probably PlayFabApiTestSuite  need to change to PlayFabClientApi

### ISSUE THREAD

**Issue by nicloay** [PlayFab/LuaSdk#10]
I'm not sure but sims like 
```
local PlayFabApiTestSuite = require("PlayFabTesting.PlayFabApiTestSuite")
```
need to change to 
```
local PlayFabClientApi = require("PlayFab.PlayFabClientApi")
```
because you use *PlayFabClientApi*  later in *init* but not define this var anywhere

**Comment by pgilmorepf** [comment]
Thanks for your comment.  I will look into this.  It seems like you are right.
I'll leave this issue open until it's confirmed and fixed.

**Comment by pgilmorepf** [comment]
You were right, thank you!
I have updated the Defold section.
