### ISSUE TITLE
Library fails to send requests after network connection is restored

### ISSUE THREAD

**Issue by DeividasK** [PlayFab/LuaSdk#12]
Hi,

I'm trying to allow players to reconnect if they go offline but later reconnect. However, that doesn't seem to be working.

### Steps to reproduce
1. Start an app without an internet connection, e.g. with Wi-fi turned off.
2. Attempt to send a request when offline, e.g. `PlayFabClientApi.LoginWithCustomID`. The request should fail as expected.
3. Turn wifi on.
4. Attemp to send a request without restarting the app.

### Actual outcome
Request fails with the following error message:
```
ERROR:SCRIPT: Unable to create HTTP connection to 'https://TitleId.playfabapi.com/Client/LoginWithCustomID?sdk=DefoldSdk_0.59.190625'. No route to host?
DEBUG:SCRIPT: 
{ --[[0x10bcefed0]]
  error = "ServiceUnavailable",
  errorCode = 1123,
  code = 0,
  status = 0,
  errorMessage = "Could not deserialize reseponse from server: "
}
```

### Expected outcome
Request should work

Let me know if there's any additional info I could provide to help with debugging.

**Comment by britzl** [comment]
It looks like you are using Defold, is this correct?

**Comment by DeividasK** [comment]
@britzl yes, it is. I'm going to close this issue as I think Playfab lib has nothing to do with this and it's to do with Defold behaviour. The reason I say this is because I've tried the same flow with `http.request()` and ran into the same issue.
