### ISSUE TITLE
Add link to Defold project sample in related readmes

### ISSUE THREAD

**Issue by subsoap** [PlayFab/LuaSdk#4]
https://github.com/britzl/playfab_example

**Comment by pgilmorepf** [comment]
That Defold project sample was a comparison point for us to improve our own code, but our SDK is not built to match that project.
Here is a link to our Defold instructions: https://github.com/PlayFab/LuaSdk/tree/master/Defold
Otherwise feel free to dive into the code and evaluate the differences.

**Comment by pgilmorepf** [comment]
Nevermind!  That project was updated to use our SDK, when I wasn't looking.  Good catch, thanks!
